### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by lukesdm** [PRBonn/semantic-kitti-api#131]
Executing `./docker.sh /path/to/dataset` fails whilst trying to build the Docker image.

This appears to be due to a dependency version issue.

```
 => ERROR [ 7/15] RUN pip3 install  scipy==0.19.1                   numpy==1.14.0                   torch==0.4.1                   opencv_python==3.4.0.12                   visp  0.5s 
------
 > [ 7/15] RUN pip3 install  scipy==0.19.1                   numpy==1.14.0                   torch==0.4.1                   opencv_python==3.4.0.12                   vispy==0.5.3      
             tensorflow==1.11.0                   PyYAML==3.13                    enum34==1.1.6                   matplotlib==3.0.3:
#10 0.429 Traceback (most recent call last):
#10 0.429   File "/usr/local/bin/pip3", line 7, in <module>
#10 0.429     from pip._internal.cli.main import main
#10 0.429   File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 66
#10 0.429     sys.stderr.write(f"ERROR: {exc}")
#10 0.429                                    ^
#10 0.429 SyntaxError: invalid syntax
------
executor failed running [/bin/sh -c pip3 install  scipy==0.19.1                   numpy==1.14.0                   torch==0.4.1                   opencv_python==3.4.0.12
   vispy==0.5.3                   tensorflow==1.11.0                   PyYAML==3.13                    enum34==1.1.6                   matplotlib==3.0.3]: exit code: 1
```

The syntax error is caused by the package using a Python 3.6 feature whilst only Python 3.5 is installed.

**Comment by jbehley** [comment]
thanks for letting us know.

hmmm, okay. maybe we have to bump the Ubuntu version of the docker container; or omit the `pip install -U pip` to avoid this.

have to look into this.

**Comment by jbehley** [comment]
Sorry that I forgot about this, however, I guess the fix from @ooodnakov fixes this, let me know if you still have issues.
