### ISSUE TITLE
Broken requirements.txt

### ISSUE THREAD

**Issue by jpaczia** [PRBonn/semantic-kitti-api#21]
Hi,

when using the supplied requirements.txt file, building vispy and PyYAML fails.
Using this [requirements.txt](https://github.com/PRBonn/semantic-kitti-api/files/3739060/requirements.txt) file all packages can be built, but I am still not able to run the visualization as described in the ReadME.
Is there any special OS or other software required?

I get the following output:

```
./visualize.py --sequence 10 --dataset /home/user/workspace/lane-segmentation/data/kitti/semantic/dataset/
/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
********************************************************************************
INTERFACE:
Dataset /home/user/workspace/lane-segmentation/data/kitti/semantic/dataset/
Config config/semantic-kitti.yaml
Sequence 10
Predictions None
ignore_semantics False
do_instances False
ignore_safety False
offset 0
********************************************************************************
Opening config file config/semantic-kitti.yaml
Sequence folder exists! Using sequence from /home/user/workspace/lane-segmentation/data/kitti/semantic/dataset/sequences/10/velodyne
Labels folder exists! Using labels from /home/user/workspace/lane-segmentation/data/kitti/semantic/dataset/sequences/10/labels
libEGL warning: DRI3: Screen seems not DRI3 capable
Using semantics in visualizer
To navigate:
	b: back (previous scan)
	n: next (next scan)
	q: quit (exit program)
WARNING: Error drawing visual <vispy.visuals.mesh.MeshVisual object at 0x7fe8dd668320>
WARNING: Traceback (most recent call last):
  File "./visualize.py", line 163, in <module>
    vis.run()
  File "/home/user/workspace/lane-segmentation/src/semantic_kitti_api/auxiliary/laserscanvis.py", line 224, in run
    vispy.app.run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/application.py", line 142, in run
    return self._backend._vispy_run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 75, in _vispy_run
    self._vispy_process_events()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 70, in _vispy_process_events
    win._on_draw()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 216, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/visual.py", line 588, in draw
    v.draw()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/mesh.py", line 517, in draw
    Visual.draw(self, *args, **kwds)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/shaders/program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/context.py", line 170, in flush_commands
    self.shared.parser.parse([('CURRENT', 0)])
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 477, in parse
    self._parse(command)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 404, in _parse
    self._gl_initialize()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 502, in _gl_initialize
    if this_version < '2.1':
  File "/usr/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.6/distutils/version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (osmesa) at 0x7fe8e8415048>> for DrawEvent
WARNING: Traceback (most recent call last):
  File "./visualize.py", line 163, in <module>
    vis.run()
  File "/home/user/workspace/lane-segmentation/src/semantic_kitti_api/auxiliary/laserscanvis.py", line 224, in run
    vispy.app.run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/application.py", line 142, in run
    return self._backend._vispy_run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 75, in _vispy_run
    self._vispy_process_events()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 70, in _vispy_process_events
    win._on_draw()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 216, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 477, in parse
    self._parse(command)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 455, in _parse
    ob.set_shaders(*args)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 651, in set_shaders
    (type_ + ' shader', errormsg))
RuntimeError: Shader compilation error in vertex shader:
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x7fe8e841c748>> for DrawEvent
WARNING: Error drawing visual <vispy.visuals.mesh.MeshVisual object at 0x7fe8dc1fb588>
WARNING: Traceback (most recent call last):
  File "./visualize.py", line 163, in <module>
    vis.run()
  File "/home/user/workspace/lane-segmentation/src/semantic_kitti_api/auxiliary/laserscanvis.py", line 224, in run
    vispy.app.run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/application.py", line 142, in run
    return self._backend._vispy_run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 75, in _vispy_run
    self._vispy_process_events()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 70, in _vispy_process_events
    win._on_draw()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 216, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/visual.py", line 588, in draw
    v.draw()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/mesh.py", line 517, in draw
    Visual.draw(self, *args, **kwds)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/visuals/shaders/program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/context.py", line 170, in flush_commands
    self.shared.parser.parse([('CURRENT', 0)])
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 477, in parse
    self._parse(command)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 404, in _parse
    self._gl_initialize()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 502, in _gl_initialize
    if this_version < '2.1':
  File "/usr/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/lib/python3.6/distutils/version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (osmesa) at 0x7fe8dc510b38>> for DrawEvent
WARNING: Traceback (most recent call last):
  File "./visualize.py", line 163, in <module>
    vis.run()
  File "/home/user/workspace/lane-segmentation/src/semantic_kitti_api/auxiliary/laserscanvis.py", line 224, in run
    vispy.app.run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/application.py", line 142, in run
    return self._backend._vispy_run()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 75, in _vispy_run
    self._vispy_process_events()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 70, in _vispy_process_events
    win._on_draw()
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/app/backends/_osmesa.py", line 216, in _on_draw
    self._vispy_canvas.events.draw(region=None)  # (0, 0, w, h)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 477, in parse
    self._parse(command)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 455, in _parse
    ob.set_shaders(*args)
  File "/home/user/workspace/lane-segmentation/env2/lib/python3.6/site-packages/vispy/gloo/glir.py", line 651, in set_shaders
    (type_ + ' shader', errormsg))
RuntimeError: Shader compilation error in vertex shader:
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x7fe8dc4bf518>> for DrawEvent
```

Thanks for any support!

**Comment by jpaczia** [comment]
No worries!

I found a solution using conda. With [this](https://github.com/PRBonn/semantic-kitti-api/files/3819692/semantic.yml.txt) environment the tool works for me (the .txt extension needs to be removed, I just added it because github does not allow .yml files)
