### ISSUE TITLE
No space left on device with proper file size 

### ISSUE THREAD

**Issue by shuangjiexu** [PRBonn/semantic-kitti-api#45]
Hi, when submit, I get error:
```
Traceback (most recent call last):
  File "/worker/worker.py", line 313, in run
    bundles = get_bundle(root_dir, 'run', bundle_url)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 173, in get_bundle
    metadata[k] = get_bundle(bundle_path, k, v)
  File "/worker/worker.py", line 133, in get_bundle
    z.extractall(bundle_path)
  File "/usr/local/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/usr/local/lib/python2.7/shutil.py", line 66, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device
```

before the submission, I test with the `validate_submission.py` script:
```
Validating zip archive "xxx/submission.zip".

  1. Checking filename.............. ✓
  2. Checking directory structure... ✓
  3. Checking file sizes............ ✓

Everything ready for submission!  🎉
```

and the size of the submission.zip is 113M.

How can I fix this? THX!

**Comment by jbehley** [comment]
Unfortunately, neither we nor you can do something here. I opened an issue on the github repository https://github.com/codalab/codalab-competitions/issues/2777 and I hope that the issue is fixed as soon as possible. I will let you know if something changes there.

**Comment by jbehley** [comment]
Hi, the issue should be resolved.

**Comment by Gofinge** [comment]
Hi, I am facing the same problem. I passed the local validation.
![image](https://user-images.githubusercontent.com/39218229/137269912-0725b9a2-4107-470a-8060-39a69ee48b26.png)
